Basic endpoints
where-banana/calendar-backend-java pull request #1
Opened 2022-09-25 23:23 UTC by Arteich

2022-09-26 10:04 UTC, alexey-savchuk requested changes
@Arteich жду ответов по всем комментариям. Дискуссия и вопросы приветствуются.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +public class Users {
Классы, описывающие таблицы в базе данных, (далее буду называть модель или model -- см. ORM) стоит называть существительным в единственном числе.
```
# например
User john = new User("John", ...);
# выглядит более разумно, чем
Users john = new Users("John", ...);
```
Имя класса-модели и имя описываемой таблицы не будут конфликтовать, так как ты используешь специальную аннотацию Table, чтобы явно указать имя таблицы.

Исправить здесь и для всех оставшихся entities.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +    private Collection<Workspaces> users;
Bad naming. Исправить во всех entities.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/entity/Credentials.java
> +    @Column(name = "email", nullable = false)
Не может быть двух одинаковых адресов.

`@Column(..., unique = true)`

Проверить все подобные аннотации.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/web/UsersController.java
> +public class UsersController {
Хочется, чтобы ты посмотрел, как пишется хороший RESTful API. Например, неплохой вариант эндпоинтов для взаимодействия с таблицей users может выглядеть так:

```
POST: http://calendar.server/users/{id} # добавление
GET: http://calendar.server/users/{id} # выборка
PUT: http://calendar.server/users/{id} # изменение
DELETE: http://calendar.server/users/{id} # удаление
```

Интерфейс становится унифицированным, и запрос к серверу зависит только от выбора HTTP глагола: POST, GET, PUT или DELETE. Это просто пример, это не значит, что сейчас нужно переделывать всё в таком виде.

Пока что нам будет достаточно 4 базовых запросов и эндпоинтов к ним.

Также было бы интересно узнать об используемых подходах к написанию services, разделению эндпоинтов по контроллерам и выбору кодов возврата (HTTP status). Советую поискать какие-нибудь статьи, пособия, выступления на конференциях на эту тему или изучить чей-нибудь готовый open source проект. При поиске можно использовать фразы "best practices", "proper way to do..." и т. д.

После этого примерные схемы API, который ты посчитаешь хорошим, можно показать мне -- лично или отправить в вк.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/web/NotesController.java
> +    public ResponseEntity<Notes> deleteNotesByDescription(@PathVariable("description") String description){
Не знаю, где это может пригодиться.

2022-09-26 10:04 UTC, savtchouk commented on calendar/src/main/java/pet/project/calendar/web/CredentialsController.java
> +public class CredentialsController {
Взаимодействие с таблицей credentials и авторизацию оставляем на потом хотя бы потому, что надо позаботиться, чтобы пароли не хранились в базе данных в сыром виде -- это лишняя забота на начальном этапе.

Убери все соответствующие сервисы и контроллеры -- entity нужно оставить!

2022-09-26 10:04 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +    @JsonIgnore
Есть несколько вариантов, где можно написать JsonIgnore. Если этот вариант не вызывает проблем, например, рекурсивного вывода JSON, то можно оставить как есть. Позже определимся с наиболее подходящим вариантом.

2022-09-26 10:12 UTC, alexey-savchuk commented
@MikhailFerapontow @Luca-Abele-101 пишите свои предложения и вопросы, если они возникают.

2022-09-28 21:34 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +public class Users {
Исправил названия entities

2022-09-28 21:34 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +    private Collection<Workspaces> users;
Исправил

2022-09-28 21:34 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/entity/Credentials.java
> +    @Column(name = "email", nullable = false)
По считал нужным только у email оставить модификатор unique

2022-09-28 21:37 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/web/UsersController.java
> +public class UsersController {
Добавил endpoints POST, PUT, DELETE для сущностей: note, event, workspace и для user DELETE и PUT

2022-09-28 21:39 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/web/NotesController.java
> +    public ResponseEntity<Notes> deleteNotesByDescription(@PathVariable("description") String description){
Пометил методы которые возможно не будут использоваться аннотацией @Deprecated. На следующем SCRUM решим какой функционал мы хотим оставить, а какой убрать

2022-09-28 21:39 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/web/CredentialsController.java
> +public class CredentialsController {
Убрал

2022-09-28 21:40 UTC, Arteich commented on calendar/src/main/java/pet/project/calendar/entity/Users.java
> +    @JsonIgnore
Избавился от рекурсивного вывода за счёт аннотации @JsonIgnore

2022-09-28 22:58 UTC, alexey-savchuk requested changes
@Arteich Разобраться с именами. Не буду смотреть содержание эндпоинтов, пока не увижу существенных изменений в подходе к проектированию REST API.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Event.java
> +    private Collection<Note> notesIntoEvents;
Слишком сложное название. Я не понял.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Credential.java
> +    private User userInfo;
Прежнее название было лучше.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Event.java
> +    private Workspace workspacesId;
Если это id, то, наверное, это должно быть поле типа int. Bad naming.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Note.java
> +    private Event eventId;
Опять id. Bad naming.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/entity/Workspace.java
> +    private Collection<Event> eventsIntoWorkspaces;
Слишком сложное название. Bad naming.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/web/NotesController.java
> +    public ResponseEntity<Notes> deleteNotesByDescription(@PathVariable("description") String description){
Тот метод, на который я указал, не помечен аннотацией.

2022-09-28 22:58 UTC, alexey-savchuk commented on calendar/src/main/java/pet/project/calendar/web/UsersController.java
> +public class UsersController {
Проделана недостаточная работа. [Полезная ссылка](https://restfulapi.net/resource-naming/).

2023-01-12 23:40 UTC, merged